### ISSUE TITLE
Locale seems to break Timestamp conversion (maybe also DateTime)

### ISSUE THREAD

**Issue by PeteK68** [prismicio/csharp-kit#10]
I can see using Fiddler that data marked as Timestamp is coming back from the server. However, when I inspect the Document, I'm left with no values.

After pulling down the source and stepping through the process of converting the json into the model, I have narrowed it down to the following:
https://github.com/prismicio/csharp-kit/blob/master/src/prismic/Fragment.cs#L410

You're expecting data to be a certain format, and I can see the raw json in Fiddler is the same format ("yyyy-MM-dd'T'HH:mm:ssZ"), however, when I inspect, the format in the JToken json has been somehow converted. My locale is the only explanation I can think of.

I have my machine's region set to United States, so I'm not sure why this is happening.

![different-format](https://cloud.githubusercontent.com/assets/1383133/12375662/2c7b6a72-bc9b-11e5-8779-ee6def8f42ef.png)

![exception](https://cloud.githubusercontent.com/assets/1383133/12375663/2c8305ac-bc9b-11e5-941a-a3831a214390.png)

**Comment by PeteK68** [comment]
Seems as Date is unaffected.

![date-unaffected](https://cloud.githubusercontent.com/assets/1383133/12375684/5e106dfc-bc9c-11e5-9c24-5a5b6b549b3f.png)

**Comment by PeteK68** [comment]
Is there any update on this? It's been 10 days.

If it makes a difference at all, we are paying customers of Prismic. This bug is causing us to consider other options.

Thanks,
Peter

**Comment by erwan** [comment]
Hi Pete,

Do the tests pass correctly on your machine?

**Comment by PeteK68** [comment]
They do, but the test coverage is inadequate to test the timestamp. Even in the test, it returns null but the test doesn't validate anything to do with the "blog-post.update" field.

See attached.

![timestamp-not-tested](https://cloud.githubusercontent.com/assets/1383133/12665868/0a780dc8-c609-11e5-8a7d-3d4c07c8678d.PNG)

**Comment by erwan** [comment]
OK, I'll start by adding a test for the timestamp and see if it passes on my machine.

**Comment by PeteK68** [comment]
Hi Erwan, any progress on this?

**Comment by erwan** [comment]
it's on my plate, I'll update the ticket as soon as I have news.

**Comment by erwan** [comment]
Yes, I confirm that JToken is not returning to original value. It'll be fixed in the next version.

**Comment by erwan** [comment]
fixed in 1.3.2
