### ISSUE TITLE
Adding a new Slice Type via the UI builder breaks all slices for that type.

### ISSUE THREAD

**Issue by benembery** [prismicio/csharp-kit#13]
Morning,

`SliceZone Parse(JToken json)` is broken for new slice Types as ` JToken fragJson = sliceJson["value"];` returns null and is not null checked. 

I've looked at the code changes in other kits and tried to replicate them. Hopefully, #14 does what you need.

**Comment by srenault** [comment]
Thanks for you contribution! 
I'll look at it ASAP.

**Comment by benembery** [comment]
Fixed in the latest version of the SDK
